# Generated by Django 4.2 on 2023-11-26 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeamList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=300)),
                ('win', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('point', models.IntegerField()),
                ('home_won', models.IntegerField()),
                ('home_lose', models.IntegerField()),
                ('home_draw', models.IntegerField()),
                ('away_won', models.IntegerField()),
                ('away_lose', models.IntegerField()),
                ('away_draw', models.IntegerField()),
                ('home_goal', models.IntegerField()),
                ('away_goal', models.IntegerField()),
                ('home_against', models.IntegerField()),
                ('away_against', models.IntegerField()),
                ('goal', models.IntegerField()),
                ('goal_against', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audience.playerinformation')),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audience.teamlist')),
            ],
        ),
    ]
